In [45]:
import pandas as pd
df = pd.read_csv('/content/bikes_data.csv')

In [46]:
df.shape

(362, 15)

In [47]:
df.columns = df.columns.str.lower().str.strip().str.replace(' ','_')

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              362 non-null    object
 1   country_of_origin    362 non-null    object
 2   model                362 non-null    object
 3   number_of_cc         362 non-null    object
 4   horsepower           362 non-null    object
 5   torque               362 non-null    object
 6   transmission_type    362 non-null    object
 7   drivetrain           362 non-null    object
 8   number_of_seating    362 non-null    int64
 9   price_(in_inr)       362 non-null    object
 10  year                 362 non-null    int64
 11  looks                362 non-null    object
 12  body_type            362 non-null    object
 13  engine_type          362 non-null    object
 14  number_of_cylinders  361 non-null    object
dtypes: int64(2), object(13)
memory usage: 42.6+ KB

In [49]:
df.dropna(inplace=True)

In [50]:
df.isna().sum()

company                0
country_of_origin      0
model                  0
number_of_cc           0
horsepower             0
torque                 0
transmission_type      0
drivetrain             0
number_of_seating      0
price_(in_inr)         0
year                   0
looks                  0
body_type              0
engine_type            0
number_of_cylinders    0
dtype: int64

In [51]:
df.duplicated().sum()

np.int64(0)

In [52]:
df.sample(5)

,company,country_of_origin,model,number_of_cc,horsepower,torque,transmission_type,drivetrain,number_of_seating,price_(in_inr),year,looks,body_type,engine_type,number_of_cylinders
199,Bajaj,India,Pulsar 125,124.9,12.7 bhp,11 Nm,4-speed constant mesh,Chain,1,"68,000",2023,"Modern, sporty",Street,"Air-cooled, 4-stroke, single-cylinder, DTS-i",1
253,Keeway,Italy,K300 R,292.4,27.1 bhp,22 Nm,6 Speed Manual,Chain Drive,1,"2,65,053",2023,Modern,Sports,"Liquid-Cooled, Single-Cylinder",Single
107,Mahindra,India,Xpulse 200,199.6,18.1 bhp @ 8500 rpm,17.3 Nm @ 6500 rpm,5-speed manual,Chain drive,2,"Rs. 1,28,990",2019,Adventure,Standard,"Single-cylinder, air-cooled, OHC",1
221,Triton Electric Bikes,China,Artemis,750,500,80 Nm,BAFANG M600 mid-drive motor,Shimano drivetrain,1,"2,50,000",2023,Modern,Mountain bike,Electric,1
118,MV Agusta,Italy,Brutale 1000 RR,998,208 hp,116 Nm,6-speed sequential,Chain,2,25.4 lakhs,2023,Aggressive,Naked,3-cylinder,3

In [60]:
df['company'] = df['company'].apply(lambda x:x.lower())
df['company'] = df['country_of_origin'].apply(lambda x:x.lower())

In [63]:
df['number_of_cc'].unique()

array(['659', '124.9', '896', '1077', '125', '250', '300', '600', '899',
       '500', '313', '853', '1,170', '999', '149', '492', '984', '1125',
       '1201', '893', '998', '1078', '650', '450', '900', '1200',
       '292.4 cc', '649.3 cc', '649 cc', '1,967 cc', '2,163 cc',
       '124.9 cc', '249.6 cc', '1103', '1262', '803', '937', '1158',
       '975', '1252', '1868', '348.36 cc', '373.2 cc', '693 cc',
       '1133 cc', '1799 cc', '1203 cc', '296', '399', '649', '948', '200',
       '390', '373', '799', '550', '124.7', '295', '199.6', '110',
       '106.7', '1400', '1700', '798', '800', '961', '160', '150', '660',
       '346', '499', '349', '411', '648', '249', '155', '124', '400',
       '2,500', '1,160', '888', '1,200', '70', '889', '321', '350',
       '1133', '248.76', '373.2', '501', '1,301', '1340', '2458', '149.5',
       '199.5', '373.3', '220.9', '100', '293', '334', '159.7', '124.8',
       '750', '29', '125cc', '250cc', '300cc', '106', '1179', '1731',
       '298', '278.2', '292.4', '1903', '647', '7.2', '11.4', '14.4',
       '292', '1330', '990', '124.6', '279.5', '49', '170', '50', '280',
       '223', '374', 'Electric', '374 cc', '249.2 cc', '250.9 cc',
       '500 cc', '600 cc', '348', '110 kW', '126 kW'], dtype=object)

In [70]:
df['number_of_cc'] = df['number_of_cc'].astype(str).str.replace('cc', '', regex=False).str.replace('kw', '', regex=False).str.replace(',', '', regex=False).str.strip()
df['number_of_cc'] = pd.to_numeric(df['number_of_cc'], errors='coerce')
df.dropna(inplace=True)

In [71]:
df['number_of_cc'].unique()

array([ 659.  ,  124.9 ,  896.  , 1077.  ,  125.  ,  250.  ,  300.  ,
        600.  ,  899.  ,  500.  ,  313.  ,  853.  , 1170.  ,  999.  ,
        149.  ,  492.  ,  984.  , 1125.  , 1201.  ,  893.  ,  998.  ,
       1078.  ,  650.  ,  450.  ,  900.  , 1200.  ,  292.4 ,  649.3 ,
        649.  , 1967.  , 2163.  ,  249.6 , 1103.  , 1262.  ,  803.  ,
        937.  , 1158.  ,  975.  , 1252.  , 1868.  ,  348.36,  373.2 ,
        693.  , 1133.  , 1799.  , 1203.  ,  296.  ,  399.  ,  948.  ,
        200.  ,  390.  ,  373.  ,  799.  ,  550.  ,  124.7 ,  295.  ,
        199.6 ,  110.  ,  106.7 , 1400.  , 1700.  ,  798.  ,  800.  ,
        961.  ,  160.  ,  150.  ,  660.  ,  346.  ,  499.  ,  349.  ,
        411.  ,  648.  ,  249.  ,  155.  ,  124.  ,  400.  , 2500.  ,
       1160.  ,  888.  ,   70.  ,  889.  ,  321.  ,  350.  ,  248.76,
        501.  , 1301.  , 1340.  , 2458.  ,  149.5 ,  199.5 ,  373.3 ,
        220.9 ,  100.  ,  293.  ,  334.  ,  159.7 ,  124.8 ,  750.  ,
         29.  ,  106.  , 1179.  , 1731.  ,  298.  ,  278.2 , 1903.  ,
        647.  ,    7.2 ,   11.4 ,   14.4 ,  292.  , 1330.  ,  990.  ,
        124.6 ,  279.5 ,   49.  ,  170.  ,   50.  ,  280.  ,  223.  ,
        374.  ,  249.2 ,  250.9 ,  348.  ])

In [196]:
df['model'].unique()

array(['RS 660', 'Tuono 660', 'RS 125', 'Shiver 900', 'Tuono 1100',
       'TNT 125', 'TNT 250', 'TNT 300', 'TNT 600i', 'TNT 899', 'TRK 251',
       'TRK 502', 'Leoncino 500', 'G 310 GS', 'G 310 R', 'F 850 GS',
       'F 850 GS Adventure', 'R 1250 GS', 'R 1250 RT', 'S 1000 RR',
       'S 1000 R', '300NK', '650NK', '650MT', '650GT', 'Hellcat',
       'Wraith', 'X132 Hellcat Combat Fighter', 'VL 125', 'V125 FI',
       'NS 250 FI', 'Roadwin 250', 'Panigale V4', 'Diavel',
       'Scrambler 800', 'Monster', 'Multistrada V4', 'Nightster',
       'Sportster S', 'Road Glide Special', 'Street Glide Special',
       'PAN America 1250', 'Fat Bob', 'Fat Boy', 'Heritage Classic',
       'CBR250R', 'CB350R', 'Hness CB350', 'CB Shine', 'Activa 125',
       'Vitpilen 401', 'Svartpilen 401', '701 Supermoto', '701 Enduro',
       'Chief Dark Horse', 'Chief Bobber Dark Horse',
       'Challenger Dark Horse', 'FTR 1200 S', 'Scout Bobber', 'Ninja 300',
       'Ninja 400', 'Ninja 650', 'Z900', 'Z H2', 'Vulcan S', '125 Duke',
       '200 Duke', '250 Duke', '390 Duke', 'RC 200', 'RC 390',
       '390 Adventure', '790 Adventure', 'Agility 125', 'Downtown 300i',
       'K-XCT 300', 'AK 550', 'Daytona 125', 'Gran Turismo 300',
       'Cafe Racer 500', 'Scrambler 650', 'V125', 'V200', 'LF125S',
       'LF200GY', 'LF250K', 'LF250GY-3', 'Mojo 300', 'Xpulse 200',
       'Gusto 125', 'Duro DZire', 'Centuro 100', 'V85 TT', 'V9 Bobber',
       'V9 Roamer', 'Audace', 'Eldorado', 'MGX-21',
       'Commando 961 Café Racer', 'Commando 961 Sport', 'Atlas', 'V4SV',
       'Aprilia SR160', 'Aprilia RS150', 'Aprilia Tuono 660',
       'Vespa VX125', 'Vespa GTS300', 'Bullet 350', 'Bullet 500',
       'Meteor 350', 'Himalayan', 'Interceptor 650', 'Continental GT 650',
       'Super Meteor 650', 'Gixxer SF 250', 'Gixxer 250', 'Intruder 150',
       'Access 125', 'Burgman Street 125', 'Joymax Z 300', 'Maxsym 400i',
       'Joyride 125', 'Fiddle III 125', 'HD 200', 'Rocket 3 R',
       'Speed Triple 1200 RR', 'Trident 660', 'Tiger 900 GT Pro',
       'Tiger 850 Sport', 'Speed Twin 900', 'Bonneville T100',
       'Bonneville T120', 'Primavera', 'Sprint', 'GTS 300', '946',
       'Elettrica', 'R1', 'MT-09', 'R3', 'FZ-25', 'XSR155',
       'RR 350 2-Stroke', 'RR 250 2-Stroke', 'RR 125 2-Stroke',
       'RR 390 4-Stroke', 'RR 250 4-Stroke', 'RR 125 4-Stroke', 'Alp 200',
       'Alp 125', 'MC 250F', 'MC 350F', 'MC 450F', 'EC 250', 'EC 300',
       'EC 250F', 'EC 300F', 'LiveWire', 'CT125', 'Super Cub',
       'Vitpilen 250', 'Svartpilen 250', 'FE 350', 'TE 300i', 'FE 501',
       'TE 501i', '1290 Super Duke R', 'Seiemmezzo 6 ½', 'X-Cape',
       'Hayabusa', 'Rocket 3', 'Pulsar 125', 'Pulsar 150', 'Platina 110',
       'Splendor Plus', 'Passion Pro', 'Glamour 125', 'HF Deluxe',
       'Apache RTR 200 4V', 'Apache RTR 200 4V FI', 'Apache RTR 160 2V',
       'Ntorq 125', 'Jupiter', 'Sport 125', 'Radeon', 'Artemis',
       'Django 125', 'Django 300', 'Metropolis 400',
       'Brutus Single Speed MTB 29', 'STX 150', 'TC', 'TC Max',
       'TS Street Hunter', 'TC Wanderer', 'Dragster 200', 'Cross Country',
       'Judge', 'Hammer', 'Octane', 'Vision', 'Furious 125',
       'Black Cafe 125', 'Muscle 125', 'Scrambler 125', 'Raw 125',
       'V302C', 'Vieste 300', 'K-Light 250V', 'K300 R', 'Sixties 300i',
       'SR125', 'Jawa 42', 'Jawa 42 Bobber', 'Jawa Perak', 'LXR 125',
       'ZSX 125', 'Milano 125', 'Vendetta 250', 'Dirt eBike X260',
       'Alpha S', 'Aquila GV650', 'Caballero 125', 'Zero S', 'Zero SR',
       'Zero SR/F', 'Zero DS', 'Zero FX', 'Bullitt', 'Revo 300',
       'Revo 125', 'Neo 110', 'Mio 110', 'TL125', 'Sixty2', 'TT125',
       'Buddy 50', 'Buddy 125', 'Buddy 170i', 'Buddy KICK',
       'Hooligan 170i', 'Roughhouse 50', 'Roughhouse 50 SPORT',
       'Rattler 50', 'Venture 50', 'Renegade Commando',
       'Renegade Sport S', 'Renegade Duty S', 'Renegade Duty Ace',
       'MQi GT', 'NQi GTS', 'MQi Plus', 'NQi Sport', 'Apache 125',
       'Meteor 125', 'City 125', 'Terrain 125', 'SM-XE 125',
       'Superdual T', 'RS 650', 'Viale 650', 'RACER 125',
       'GRAN TURISMO 125', 'CUx', 'CPx', 'CT 125', 'Kent 125',
       'Imperiale 400', 'Leoncino 250', '502 C', 'TNT 600RR',
       'Cadwell 125', 'Tempest Scrambler 125', 'Tempest Roadster 125',
       '350R', '350T', '350X', 'GK350', 'Akita', 'FSR', 'GT-SR', 'GT-SS',
       'Hilts', 'Mastiff', 'Mongrel', 'Razorback', 'RS-13', 'Sabbath'],
      dtype=object)

In [199]:
df['model'] = df['model'].str.lower()
df['model'].unique()

array(['rs 660', 'tuono 660', 'rs 125', 'shiver 900', 'tuono 1100',
       'tnt 125', 'tnt 250', 'tnt 300', 'tnt 600i', 'tnt 899', 'trk 251',
       'trk 502', 'leoncino 500', 'g 310 gs', 'g 310 r', 'f 850 gs',
       'f 850 gs adventure', 'r 1250 gs', 'r 1250 rt', 's 1000 rr',
       's 1000 r', '300nk', '650nk', '650mt', '650gt', 'hellcat',
       'wraith', 'x132 hellcat combat fighter', 'vl 125', 'v125 fi',
       'ns 250 fi', 'roadwin 250', 'panigale v4', 'diavel',
       'scrambler 800', 'monster', 'multistrada v4', 'nightster',
       'sportster s', 'road glide special', 'street glide special',
       'pan america 1250', 'fat bob', 'fat boy', 'heritage classic',
       'cbr250r', 'cb350r', 'hness cb350', 'cb shine', 'activa 125',
       'vitpilen 401', 'svartpilen 401', '701 supermoto', '701 enduro',
       'chief dark horse', 'chief bobber dark horse',
       'challenger dark horse', 'ftr 1200 s', 'scout bobber', 'ninja 300',
       'ninja 400', 'ninja 650', 'z900', 'z h2', 'vulcan s', '125 duke',
       '200 duke', '250 duke', '390 duke', 'rc 200', 'rc 390',
       '390 adventure', '790 adventure', 'agility 125', 'downtown 300i',
       'k-xct 300', 'ak 550', 'daytona 125', 'gran turismo 300',
       'cafe racer 500', 'scrambler 650', 'v125', 'v200', 'lf125s',
       'lf200gy', 'lf250k', 'lf250gy-3', 'mojo 300', 'xpulse 200',
       'gusto 125', 'duro dzire', 'centuro 100', 'v85 tt', 'v9 bobber',
       'v9 roamer', 'audace', 'eldorado', 'mgx-21',
       'commando 961 café racer', 'commando 961 sport', 'atlas', 'v4sv',
       'aprilia sr160', 'aprilia rs150', 'aprilia tuono 660',
       'vespa vx125', 'vespa gts300', 'bullet 350', 'bullet 500',
       'meteor 350', 'himalayan', 'interceptor 650', 'continental gt 650',
       'super meteor 650', 'gixxer sf 250', 'gixxer 250', 'intruder 150',
       'access 125', 'burgman street 125', 'joymax z 300', 'maxsym 400i',
       'joyride 125', 'fiddle iii 125', 'hd 200', 'rocket 3 r',
       'speed triple 1200 rr', 'trident 660', 'tiger 900 gt pro',
       'tiger 850 sport', 'speed twin 900', 'bonneville t100',
       'bonneville t120', 'primavera', 'sprint', 'gts 300', '946',
       'elettrica', 'r1', 'mt-09', 'r3', 'fz-25', 'xsr155',
       'rr 350 2-stroke', 'rr 250 2-stroke', 'rr 125 2-stroke',
       'rr 390 4-stroke', 'rr 250 4-stroke', 'rr 125 4-stroke', 'alp 200',
       'alp 125', 'mc 250f', 'mc 350f', 'mc 450f', 'ec 250', 'ec 300',
       'ec 250f', 'ec 300f', 'livewire', 'ct125', 'super cub',
       'vitpilen 250', 'svartpilen 250', 'fe 350', 'te 300i', 'fe 501',
       'te 501i', '1290 super duke r', 'seiemmezzo 6 ½', 'x-cape',
       'hayabusa', 'rocket 3', 'pulsar 125', 'pulsar 150', 'platina 110',
       'splendor plus', 'passion pro', 'glamour 125', 'hf deluxe',
       'apache rtr 200 4v', 'apache rtr 200 4v fi', 'apache rtr 160 2v',
       'ntorq 125', 'jupiter', 'sport 125', 'radeon', 'artemis',
       'django 125', 'django 300', 'metropolis 400',
       'brutus single speed mtb 29', 'stx 150', 'tc', 'tc max',
       'ts street hunter', 'tc wanderer', 'dragster 200', 'cross country',
       'judge', 'hammer', 'octane', 'vision', 'furious 125',
       'black cafe 125', 'muscle 125', 'scrambler 125', 'raw 125',
       'v302c', 'vieste 300', 'k-light 250v', 'k300 r', 'sixties 300i',
       'sr125', 'jawa 42', 'jawa 42 bobber', 'jawa perak', 'lxr 125',
       'zsx 125', 'milano 125', 'vendetta 250', 'dirt ebike x260',
       'alpha s', 'aquila gv650', 'caballero 125', 'zero s', 'zero sr',
       'zero sr/f', 'zero ds', 'zero fx', 'bullitt', 'revo 300',
       'revo 125', 'neo 110', 'mio 110', 'tl125', 'sixty2', 'tt125',
       'buddy 50', 'buddy 125', 'buddy 170i', 'buddy kick',
       'hooligan 170i', 'roughhouse 50', 'roughhouse 50 sport',
       'rattler 50', 'venture 50', 'renegade commando',
       'renegade sport s', 'renegade duty s', 'renegade duty ace',
       'mqi gt', 'nqi gts', 'mqi plus', 'nqi sport', 'apache 125',
       'meteor 125', 'city 125', 'terrain 125', 'sm-xe 125',
       'superdual t', 'rs 650', 'viale 650', 'racer 125',
       'gran turismo 125', 'cux', 'cpx', 'ct 125', 'kent 125',
       'imperiale 400', 'leoncino 250', '502 c', 'tnt 600rr',
       'cadwell 125', 'tempest scrambler 125', 'tempest roadster 125',
       '350r', '350t', '350x', 'gk350', 'akita', 'fsr', 'gt-sr', 'gt-ss',
       'hilts', 'mastiff', 'mongrel', 'razorback', 'rs-13', 'sabbath'],
      dtype=object)

In [77]:
df['horsepower'] = df['horsepower'].str.split().str[0]
df['horsepower'] = df['horsepower'].str.replace('hp','')
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
df.dropna(inplace=True)
df['horsepower'].unique()

array([100.  ,  15.  ,  95.  , 175.  ,  11.  ,  27.  ,  39.  ,  85.  ,
       116.  ,  47.  ,  34.  , 136.  , 199.  , 165.  ,  11.7 ,  41.  ,
        45.  , 110.  ,  96.  , 105.  ,  80.  ,  65.  ,  60.  ,  86.  ,
       115.  ,  33.99,  61.18,  70.7 ,  62.54, 205.  , 190.  , 227.  ,
        10.8 ,  11.2 ,  27.6 , 221.  , 159.6 ,  73.  , 111.  , 168.  ,
        88.5 , 120.7 ,  92.5 , 150.2 ,  94.  ,  26.5 ,  31.  ,  29.6 ,
        10.5 ,   8.75,  43.  ,  75.  , 108.  , 122.  , 120.  ,  67.  ,
       125.  , 197.  ,  25.  ,  30.  ,  10.  ,  29.  ,  12.5 ,  25.8 ,
        38.  ,  10.19,  12.9 ,   9.4 ,  12.  ,  18.5 ,  22.5 ,  18.1 ,
        10.7 ,   8.5 , 147.  , 208.  , 140.  , 177.  ,  11.3 ,  17.7 ,
         9.5 ,  23.8 ,  19.8 ,  27.2 ,  20.2 ,  24.5 ,  47.6 ,  14.8 ,
         8.7 ,  32.  ,  33.  ,   9.  ,  17.  , 167.  ,  89.  ,  97.  ,
        79.  ,  12.1 ,   4.  , 200.  , 117.  ,  42.  ,  26.  ,  18.  ,
        40.  ,  35.  ,  24.  ,  20.  ,  37.  ,  44.  ,  52.  ,  10.2 ,
        30.84,  43.5 ,  39.3 ,  44.2 ,  51.5 ,  55.7 ,  60.8 , 158.  ,
        12.7 ,  14.5 ,  39.4 ,  19.05,   8.6 ,   9.1 ,  18.4 ,   8.3 ,
        27.33,  30.64,  19.7 ,  15.3 ,   9.7 , 500.  , 250.  ,  36.  ,
         5.  ,  20.07, 104.  ,  29.9 ,  27.1 ,   9.56,  13.6 ,  14.  ,
        21.  ,  67.7 ,  68.  ,  23.11,  30.4 ,  74.  ,  92.  ,  11.5 ,
        13.2 ,  50.  ,   9.39,  19.5 ,   3.3 ,  11.6 ,   3.5 ,   4.5 ,
        25.5 ,  17.5 ,  11.1 ,  54.38,  55.  ,   3.  ,  47.5 , 118.  ,
        11.83,  38.2 ])

In [89]:
df['torque'] = df['torque'].str.split().str[0]
df['torque'] = df['torque'].str.replace('hp','')
df['torque'] = pd.to_numeric(df['torque'], errors='coerce')
# df.dropna(inplace=True)
df['torque'].unique()

array([ 67.  ,  12.  ,  90.  , 121.  ,  10.8 ,  21.2 ,  26.5 ,  54.6 ,
        86.3 ,  46.  ,  28.  ,  92.  , 112.  , 113.  ,  11.9 ,  38.  ,
        37.  ,  97.  ,  98.  , 103.  ,  66.  ,  95.  ,  54.  ,  40.  ,
        77.  , 105.  ,  21.5 ,  45.  ,  55.  ,  49.  , 135.  , 125.  ,
       143.  ,  10.2 ,  22.4 , 124.  ,  93.  ,  47.  ,  69.  ,  65.  ,
        94.  , 118.  ,  19.4 ,  27.3 ,  30.  ,  10.3 ,  72.  , 114.  ,
       178.  , 110.  ,  27.  ,  39.  ,  98.6 , 140.  ,  62.  ,  19.  ,
        24.  ,  88.  ,   9.5 ,  23.5 ,  50.  ,   9.2 ,  16.  ,  14.  ,
        18.  ,  21.  ,  17.3 ,  10.5 ,   8.5 ,  73.8 ,  59.4 ,  86.  ,
        89.  , 116.  ,  11.5 ,  14.2 ,   9.8 ,  26.  ,  41.  ,  32.  ,
        52.  ,  52.3 ,  22.6 ,  34.  ,  10.  ,   9.  , 163.  ,  59.  ,
        64.  ,  85.  ,  87.  ,  12.2 ,   8.8 ,  56.  ,  29.  ,  18.6 ,
        14.7 ,  22.  ,  20.  ,  42.  ,  25.  ,  10.4 ,  35.  ,  48.  ,
       150.  , 221.  , 111.  ,  11.  ,  13.  ,  17.35,   8.9 ,   9.7 ,
        17.1 ,  10.6 ,   8.05,  27.02,  32.74,  16.8 ,  18.1 ,  13.7 ,
         9.4 ,  80.  ,  17.  , 100.  ,  76.  , 120.  , 184.3 , 192.3 ,
        22.5 , 106.  , 130.  , 190.  ,  22.8 , 115.  ,   8.3 ,   3.5 ,
        12.8 ,  15.5 ,   3.8 ,   4.8 ,  23.  ,  16.5 ,  11.8 ,  53.5 ,
        15.  ,  24.5 ,  32.8 ,  58.  ])

In [91]:
df['transmission_type'].unique()

array(['6-speed quickshifter', '6-speed manual', 'Manual',
       '6-speed Manual', '5-speed manual', 'CVT',
       '6-speed sequential manual', '6-speed automatic', 'Automatic',
       '4-speed manual', '6-speed sequential', 'Six-speed sequential',
       'Five-speed constant mesh', 'Six-speed', 'Direct drive',
       'Constant Mesh, 6-speed', '4-speed constant mesh',
       '5-speed constant mesh', '6-speed constant mesh', '5-speed',
       '4-speed', 'BAFANG M600 mid-drive motor',
       'Bafang BBS02 mid-drive motor', 'BLDC hub motor', 'Single Speed',
       'Six-speed constant mesh', '6 Speed Manual', 'CVT Automatic',
       'CVT automatic', '6-Speed'], dtype=object)

In [137]:
def clean_transmission_type(df):
    df['transmission_type'] = df['transmission_type'].str.lower()

    def extract_transmission_keyword(text):
        s_text = str(text)
        parts = s_text.replace(' ', '-').split('-')
        if len(parts) == 1:
            return parts[0]
        elif len(parts) == 2:
            return parts[1]
        else:
            return parts[-1]

    df['transmission_type'] = df['transmission_type'].apply(extract_transmission_keyword)
    return df

In [140]:
df = clean_transmission_type(df)
df['transmission_type'].unique()

array(['quickshifter', 'manual', 'cvt', 'automatic', 'sequential', 'mesh',
       'speed', 'drive', 'motor'], dtype=object)

In [151]:
df['drivetrain'] = df['drivetrain'].str.lower().str.replace('-','').str.strip()
df['drivetrain'].unique()

array(['chain', 'shaft', 'belt', 'chain drive', 'shaft drive',
       'belt drive', 'automatic', 'cvt', 'electric',
       'permanent magnet synchronous motor', 'shimano drivetrain',
       'front suspension', 'singlegear', 'automatic cvt',
       'dualmotor, allwheel drive', 'vtwin, liquidcooled, 4stroke',
       'front wheel drive', 'parallel twin'], dtype=object)

In [158]:
df.rename(columns={'number_of_seating':'seating'}, inplace=True)
df['seating']= df['seating'].astype('int')

In [166]:
df.rename(columns={'price_(in_inr)':'price'}, inplace=True)
df['price'].unique()

array(['INR 10,99,000', 'INR 11,99,000', 'INR 4,49,000', 'INR 13,99,000',
       'INR 19,99,000', '1,25,000', '1,75,000', '2,00,000', '4,00,000',
       '6,00,000', '2,25,000', '3,50,000', '3,25,000', '3,00,000',
       '2,50,000', '8,00,000', '12,00,000', '14,00,000', '16,00,000',
       '1.50 lakhs', '1.25 lakhs', '3.50 lakhs', '3.75 lakhs', '4 lakhs',
       '4.5 lakhs', '10 lakhs', '13 lakhs', '11 lakhs', '12 lakhs',
       '1.5 lakhs', '8 lakhs', '15 lakhs', '20 lakhs', 'Rs. 2,29,000',
       'Rs. 4,29,000', 'Rs. 5,29,000', 'Rs. 5,59,000', '$55,000',
       '$50,000', '$100,000', 'Rs. 1,29,500', 'Rs. 1,40,000',
       'Rs. 2,39,000', 'Rs. 2,59,000', '27.41 Lakh', '25.91 Lakh',
       '9.39 Lakh', '12.95 Lakh', '21.48 Lakh', '17,49,000', '18,79,000',
       '40,49,000', '37,49,000', '24,49,000', '20,49,000', '26,59,000',
       '1,45,000', '1,85,000', '1,65,000', '65,000', '62,000', '3,35,000',
       '6,50,000', '7,50,000', '22,999', '23,999', '25,999', '19,999',
       '14,999', '3.43 Lakh', '5.19 Lakh', '6.65 Lakh', '9.11 Lakh',
       '23.02 Lakh', '6.95 Lakh', '1.78 Lakh', '1.92 Lakh', '2.20 Lakh',
       '3.10 Lakh', '2.05 Lakh', '3.30 Lakh', '3.60 Lakh', '5.50 Lakh',
       '75,000', '1,50,000', '1,60,000', 'Rs. 1,05,000', 'Rs. 1,50,000',
       'Rs. 2,00,000', 'Rs. 2,50,000', '₹ 80,000 - ₹ 90,000',
       '₹ 1,00,000 - ₹ 1,30,000', '₹ 50,000 - ₹ 60,000',
       '₹ 70,000 - ₹ 80,000', '₹ 1,00,000 - ₹ 1,20,000', 'Rs. 2,08,000',
       'Rs. 1,28,990', 'Rs. 69,990', 'Rs. 54,990', 'Rs. 54,095',
       '15.40 lakh', '13.6 lakh', '13.3 lakh', '14.8 lakh', '17.5 lakh',
       '24.9 lakh', '18.9 lakhs', '25.4 lakhs', '22.8 lakhs',
       '21.1 lakhs', '20.7 lakhs', 'Rs. 20.99 lakh', 'Rs. 32.99 lakh',
       'Rs. 35.99 lakh', 'Rs. 1.25 lakh', 'Rs. 1.55 lakh',
       'Rs. 3.15 lakh', 'Rs. 1.15 lakh', 'Rs. 2.15 lakh', 'Rs. 1.47 lakh',
       'Rs. 1.97 lakh', 'Rs. 1.65 lakh', 'Rs. 2.20 lakh', 'Rs. 2.79 lakh',
       'Rs. 2.99 lakh', 'INR 3,49,000 - 3,79,000',
       '₹1.69 lakh - ₹1.89 lakh', '₹1.39 lakh - ₹1.59 lakh',
       '₹1.15 lakh - ₹1.25 lakh', '₹67,500', '₹78,300', '4,50,000',
       '1,10,000', '95,000', '20,19,312', '17,95,000', '7,45,000',
       '14,99,000', '11,95,000', '8,49,000', '9,69,000', '11,09,000',
       '1,32,000', '1,15,000', '20,00,000', '8,50,000', '5,50,000',
       '12,50,000', '11,00,000', '10,50,000', '13,00,000', '14,50,000',
       '11,50,000', '35,00,000', '1,35,000', '2,19,000', '2,80,000',
       '2,90,000', '4,20,000', '5,30,000', '17,00,000',
       '6.89 - 7.10 Lakh', '7.20 - 7.50 Lakh', '16.90 Lakh', '21.40 Lakh',
       '14 lakhs (expected)', '68,000', '85,000', '1.99 lakhs',
       '1.13 lakhs', '58,000', '64,000', '1.15 lakhs', '1.22 lakhs',
       '72,000', '51,000', '1.67 lakhs', '2.15 lakhs', '1,28,000',
       '1,34,000', '99,500', '69,900', '62,275', '78,750', '72,750',
       '1,00,000', '80,000', '2,40,000', '14,250', '100,000', '1,40,000',
       '1,30,000', '8.29 lakh', '15,00,000', '22,00,000', '1,05,000',
       '1,20,000', '3,89,000', '3,24,992', '3,19,983', '2,65,053',
       '3,29,984', '1,19,999', 'Rs. 1,67,000', 'Rs. 1,84,000',
       'Rs. 2,15,000', 'Rs. 1,65,000', 'Rs. 1,75,000', 'Rs. 1,35,000',
       'Rs. 2,25,000', '1.1 Lakhs', '1.5 Lakhs', '1 Lakhs', '2.5 Lakhs',
       '3.37 lakhs (ex-showroom)', '4.2 lakhs (ex-showroom)',
       '2.2 lakhs (ex-showroom)', '12,99,500', '15,99,500', '19,99,500',
       '16,99,500', '13,99,500', '55,000', '40,000', '35,000',
       '18.5 lakhs', '13.5 lakhs', '88,000', '1,99,000', '45,000',
       '60,000', '70,000', '90,000', '30,000', '1,64,000', '1,57,000',
       '1,49,999', '1,59,999', '1,29,999', '1,44,999', '99,999',
       '1,39,999', '6.8 Lakh', '8.5 Lakh', '7.8 Lakh', '1.2 Lakh',
       '1.3 Lakh', '1.4 Lakh', '1.5 Lakh', '1.8 Lakh', '4.5 Lakh',
       '2.7 Lakh', '2.1 Lakh', '1.1 Lakh', '1 Lakh', 'Rs. 2,34,914',
       'Rs. 2,59,900', 'Rs. 2,99,000', 'Rs. 4,69,000', 'Rs. 6,19,000',
       'Rs. 5,60,000', 'Rs. 5,85,000', 'Rs. 7,50,000', '1,499,000',
       '1,549,000', '3.59 lakhs (ex-showroom)', '3,47,000', '3,57,000',
       '3,67,000', 'Rs. 3.59 lakh', 'Rs. 4.99 lakh', 'Rs. 5.49 lakh',
       'Rs. 5.99 lakh', 'Rs. 5.29 lakh', 'Rs. 6.49 lakh', 'Rs. 6.99 lakh',
       'Rs. 6.79 lakh', 'Rs. 7.49 lakh', '7,20,000', '6,89,000'],
      dtype=object)

In [ ]:
def clean_price(df):
    df['price'] = df['price'].str.replace('₹', '', regex=False).str.replace('$','',regex=False).str.replace('Rs.','',regex=False).str.replace(',','')
    df['price']

In [178]:
# 1. Standardize initial cleaning (remove currency symbols, Rs., commas, INR, and specific parenthetical text)
df['price'] = df['price'].astype(str).str.lower() \
                        .str.replace('₹', '', regex=False) \
                        .str.replace('$', '', regex=False) \
                        .str.replace('rs.', '', regex=False) \
                        .str.replace(',', '', regex=False) \
                        .str.replace('inr', '', regex=False) \
                        .str.replace('(ex-showroom)', '', regex=False) \
                        .str.replace('(expected)', '', regex=False) \
                        .str.strip()

# 2. Handle ranges (take the first value in a range)
df['price'] = df['price'].apply(lambda x: x.split('-')[0].strip() if isinstance(x, str) and '-' in x else x)

# 3. Convert 'lakh' values to numeric and multiply by 100,000
def convert_lakhs_and_to_numeric(price_str):
    if isinstance(price_str, str):
        price_str = price_str.strip()
        # Check if 'lakh' is present
        if 'lakh' in price_str:
            num_part = price_str.replace('lakh', '').strip()
            try:
                return (num_part) * 100000
            except ValueError:
                return price_str
        else:
            try:
                return (price_str)
            except ValueError:
                return price_str
    return price_str

df['price'] = df['price'].apply(convert_lakhs_and_to_numeric)

# 4. Convert to numeric, coercing any remaining errors to NaN
df['price'] = pd.to_numeric(df['price'], errors='coerce')

# 5. Drop rows with NaN prices after conversion, as these are unparseable values
df.dropna(subset=['price'], inplace=True)

# 6. Ensure 'x.xx' format by rounding to 2 decimal places (underlying type is float)
df['price'] = df['price'].round(2)

df['price'].unique()

array([1.099000e+06, 1.199000e+06, 4.490000e+05, 1.399000e+06,
       1.999000e+06, 1.250000e+05, 1.750000e+05, 2.000000e+05,
       4.000000e+05, 6.000000e+05, 2.250000e+05, 3.500000e+05,
       3.250000e+05, 3.000000e+05, 2.500000e+05, 8.000000e+05,
       1.200000e+06, 1.400000e+06, 1.600000e+06, 2.290000e+05,
       4.290000e+05, 5.290000e+05, 5.590000e+05, 5.500000e+04,
       5.000000e+04, 1.000000e+05, 1.295000e+05, 1.400000e+05,
       2.390000e+05, 2.590000e+05, 2.741000e+06, 2.591000e+06,
       9.390000e+05, 1.295000e+06, 2.148000e+06, 1.749000e+06,
       1.879000e+06, 4.049000e+06, 3.749000e+06, 2.449000e+06,
       2.049000e+06, 2.659000e+06, 1.450000e+05, 1.850000e+05,
       1.650000e+05, 6.500000e+04, 6.200000e+04, 3.350000e+05,
       6.500000e+05, 7.500000e+05, 2.299900e+04, 2.399900e+04,
       2.599900e+04, 1.999900e+04, 1.499900e+04, 3.430000e+05,
       5.190000e+05, 6.650000e+05, 9.110000e+05, 2.302000e+06,
       6.950000e+05, 1.780000e+05, 1.920000e+05, 2.200000e+05,
       3.100000e+05, 2.050000e+05, 3.300000e+05, 3.600000e+05,
       5.500000e+05, 7.500000e+04, 1.500000e+05, 1.600000e+05,
       1.050000e+05, 8.000000e+04, 7.000000e+04, 2.080000e+05,
       1.289900e+05, 6.999000e+04, 5.499000e+04, 5.409500e+04,
       1.540000e+06, 1.360000e+06, 1.330000e+06, 1.480000e+06,
       1.750000e+06, 2.490000e+06, 2.099000e+06, 3.299000e+06,
       3.599000e+06, 1.550000e+05, 3.150000e+05, 1.150000e+05,
       2.150000e+05, 1.470000e+05, 1.970000e+05, 2.790000e+05,
       2.990000e+05, 3.490000e+05, 1.690000e+05, 1.390000e+05,
       6.750000e+04, 7.830000e+04, 4.500000e+05, 1.100000e+05,
       9.500000e+04, 2.019312e+06, 1.795000e+06, 7.450000e+05,
       1.499000e+06, 1.195000e+06, 8.490000e+05, 9.690000e+05,
       1.109000e+06, 1.320000e+05, 2.000000e+06, 8.500000e+05,
       1.250000e+06, 1.100000e+06, 1.050000e+06, 1.300000e+06,
       1.450000e+06, 1.150000e+06, 3.500000e+06, 1.350000e+05,
       2.190000e+05, 2.800000e+05, 2.900000e+05, 4.200000e+05,
       5.300000e+05, 1.700000e+06, 6.890000e+00, 7.200000e+00,
       1.690000e+06, 2.140000e+06, 6.800000e+04, 8.500000e+04,
       5.800000e+04, 6.400000e+04, 7.200000e+04, 5.100000e+04,
       1.280000e+05, 1.340000e+05, 9.950000e+04, 6.990000e+04,
       6.227500e+04, 7.875000e+04, 7.275000e+04, 2.400000e+05,
       1.425000e+04, 1.300000e+05, 8.290000e+05, 1.500000e+06,
       2.200000e+06, 1.200000e+05, 3.890000e+05, 3.249920e+05,
       3.199830e+05, 2.650530e+05, 3.299840e+05, 1.199990e+05,
       1.670000e+05, 1.840000e+05, 1.299500e+06, 1.599500e+06,
       1.999500e+06, 1.699500e+06, 1.399500e+06, 4.000000e+04,
       3.500000e+04, 8.800000e+04, 1.990000e+05, 4.500000e+04,
       6.000000e+04, 9.000000e+04, 3.000000e+04, 1.640000e+05,
       1.570000e+05, 1.499990e+05, 1.599990e+05, 1.299990e+05,
       1.449990e+05, 9.999900e+04, 1.399990e+05, 6.800000e+05,
       7.800000e+05, 1.800000e+05, 2.700000e+05, 2.100000e+05,
       2.349140e+05, 2.599000e+05, 4.690000e+05, 6.190000e+05,
       5.600000e+05, 5.850000e+05, 1.549000e+06, 3.470000e+05,
       3.570000e+05, 3.670000e+05, 3.590000e+05, 4.990000e+05,
       5.490000e+05, 5.990000e+05, 6.490000e+05, 6.990000e+05,
       6.790000e+05, 7.490000e+05, 7.200000e+05, 6.890000e+05])

In [180]:
df['price'].describe()

count    3.050000e+02
mean     5.924998e+05
std      7.347827e+05
min      6.890000e+00
25%      1.200000e+05
50%      2.500000e+05
75%      8.000000e+05
max      4.049000e+06
Name: price, dtype: float64

In [191]:
df['looks'].unique()

array(['Sport', 'Adventure', 'Classy', 'Sporty', 'Retro', 'Touring',
       'Modern', 'Bold', 'Sleek', 'Classic', 'Modern, stylish',
       'Modern, rugged', 'Modern, sporty', 'Modern, off-road',
       'Classic, rugged', 'Classic, bobber', 'Modern, muscular',
       'Modern, bobber', 'Aggressive', 'Race-inspired', 'Commuter',
       'Bobber', 'Cruiser', 'Practical', 'Classy, cruiser',
       'Sporty, aggressive', 'Adventure, touring', 'Adventure, sporty',
       'Classic, stylish', 'Classic, vintage',
       'Sporty, beginner-friendly', 'Motocross', 'Enduro',
       'Simple, reliable', 'Fun', 'Budget', 'Futuristic', 'Rugged',
       'Retro-modern', 'Modern, aggressive', 'Naked', 'Dirt', 'Stylish',
       'Urban', 'Retro-inspired'], dtype=object)

In [194]:
df['looks'] = df['looks'].str.lower().str.replace('-','').str.replace(',','').str.strip()
df['looks']

0              sport
1              sport
2              sport
3          adventure
4          adventure
           ...
352    retroinspired
353    retroinspired
354    retroinspired
360           modern
361            retro
Name: looks, Length: 305, dtype: object

In [202]:
df['body_type'].unique()

array(['Naked', 'Racing', 'Sport', 'Adventure', 'Cruiser', 'Roadster',
       'Superbike', 'Sport-touring', 'Fighter', 'Scooter', 'Sports',
       'Standard', 'Tourer', 'Supermoto', 'Enduro', 'Cafe Racer',
       'Scrambler', 'Café racer', 'Sports bike', 'Adventure bike',
       'Naked bike', 'Cafe racer', 'Street bike', 'Maxi-Scooter',
       'Naked Bike', 'Sportbike', 'Retro', 'Dual-sport', 'Motocross',
       'Trail', 'Street', 'commuter', 'Mountain bike', 'Hybrid bike',
       'Electric scooter', 'Mountain Bike', 'Street Bike',
       'Streetfighter', 'Touring', 'Sports Naked', 'Commuter', 'Bobber',
       'Dirt bike', 'Off-road', 'Cargo', 'Classic', 'Trail Bike',
       'Adventure touring', 'Supersport', 'Adventure tourer',
       'Street scrambler', 'Tracker'], dtype=object)

In [203]:
df['body_type'] = df['body_type'].str.lower().str.replace('-','').str.replace(',','').str.strip()
df['body_type'].unique()

array(['naked', 'racing', 'sport', 'adventure', 'cruiser', 'roadster',
       'superbike', 'sporttouring', 'fighter', 'scooter', 'sports',
       'standard', 'tourer', 'supermoto', 'enduro', 'cafe racer',
       'scrambler', 'café racer', 'sports bike', 'adventure bike',
       'naked bike', 'street bike', 'maxiscooter', 'sportbike', 'retro',
       'dualsport', 'motocross', 'trail', 'street', 'commuter',
       'mountain bike', 'hybrid bike', 'electric scooter',
       'streetfighter', 'touring', 'sports naked', 'bobber', 'dirt bike',
       'offroad', 'cargo', 'classic', 'trail bike', 'adventure touring',
       'supersport', 'adventure tourer', 'street scrambler', 'tracker'],
      dtype=object)

In [205]:
df['engine_type'].unique()

array(['Parallel-twin', 'Single-cylinder', 'V-twin', 'Single', 'Triple',
       'Boxer', 'Liquid-cooled inline-4', 'V4', 'L-Twin',
       'Liquid-cooled, parallel-twin', 'Liquid-cooled, four-cylinder',
       'Supercharged, four-cylinder',
       'Air Cooled, Single Cylinder, 4-Stroke',
       'Liquid Cooled, Single Cylinder, 4-Stroke',
       'Single-cylinder, liquid-cooled, DOHC',
       'Single-cylinder, air-cooled, OHC', 'Air-cooled, parallel-twin',
       'Liquid-cooled, V4', 'Air-cooled, single-cylinder',
       'Liquid-cooled, single-cylinder', 'Parallel twin',
       'Liquid-cooled, 4-stroke, single-cylinder',
       'Air-cooled, 4-stroke, single-cylinder', '3-cylinder',
       '2-cylinder', '1-cylinder', 'Electric', '4-cylinder', 'Two-stroke',
       'Four-stroke', 'In-line-four', 'In-line-three',
       'Air-cooled, 4-stroke, single-cylinder, DTS-i',
       'Single-cylinder, air-cooled',
       'Single-cylinder, fuel-injected, air-cooled', '2', '4-stroke',
       'Liquid-cooled', 'Air-Cooled, Single-Cylinder',
       'Liquid-Cooled, Single-Cylinder', 'Single-cylinder, liquid-cooled',
       'Single cylinder', '2-stroke',
       'Single-cylinder, liquid-cooled, 4-stroke',
       'Single-cylinder, air-cooled, 4-stroke', 'Air-Cooled',
       'Liquid-Cooled', 'Parallel-twin, liquid-cooled',
       'Liquid-cooled, DOHC'], dtype=object)

In [206]:
df['engine_type'] = df['engine_type'].str.lower().str.replace('-','').str.replace(',','').str.strip()
df['engine_type'].unique()

array(['paralleltwin', 'singlecylinder', 'vtwin', 'single', 'triple',
       'boxer', 'liquidcooled inline4', 'v4', 'ltwin',
       'liquidcooled paralleltwin', 'liquidcooled fourcylinder',
       'supercharged fourcylinder', 'air cooled single cylinder 4stroke',
       'liquid cooled single cylinder 4stroke',
       'singlecylinder liquidcooled dohc', 'singlecylinder aircooled ohc',
       'aircooled paralleltwin', 'liquidcooled v4',
       'aircooled singlecylinder', 'liquidcooled singlecylinder',
       'parallel twin', 'liquidcooled 4stroke singlecylinder',
       'aircooled 4stroke singlecylinder', '3cylinder', '2cylinder',
       '1cylinder', 'electric', '4cylinder', 'twostroke', 'fourstroke',
       'inlinefour', 'inlinethree',
       'aircooled 4stroke singlecylinder dtsi',
       'singlecylinder aircooled',
       'singlecylinder fuelinjected aircooled', '2', '4stroke',
       'liquidcooled', 'singlecylinder liquidcooled', 'single cylinder',
       '2stroke', 'singlecylinder liquidcooled 4stroke',
       'singlecylinder aircooled 4stroke', 'aircooled',
       'paralleltwin liquidcooled', 'liquidcooled dohc'], dtype=object)

In [208]:
df['number_of_cylinders'].unique()

array(['2', '1', '3', '4', '90°', '0', 'Single', 'One', 'Two', 'Three',
       'Parallel-Twin'], dtype=object)

In [222]:
df['number_of_cylinders'] = df['number_of_cylinders'].str.replace('Single','1').str.replace('Parallel-Twin','2').str.replace('One','1').str.replace('Two','2').str.replace('Three','3').replace('90°','1')
df['number_of_cylinders'] = df['number_of_cylinders'].astype(int)
df['number_of_cylinders'].unique()
df['number_of_cylinders'].describe()

count    305.000000
mean       1.347541
std        0.686238
min        0.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        4.000000
Name: number_of_cylinders, dtype: float64

In [223]:
df_cleaned = df.copy()
df_cleaned

,company,country_of_origin,model,number_of_cc,horsepower,torque,transmission_type,drivetrain,seating,price,year,looks,body_type,engine_type,number_of_cylinders
0,italy,Italy,rs 660,659.0,100.0,67.0,quickshifter,chain,2,1099000.0,2021,sport,naked,paralleltwin,2
1,italy,Italy,tuono 660,659.0,100.0,67.0,quickshifter,chain,2,1199000.0,2021,sport,naked,paralleltwin,2
2,italy,Italy,rs 125,124.9,15.0,12.0,manual,chain,2,449000.0,2022,sport,racing,singlecylinder,1
3,italy,Italy,shiver 900,896.0,95.0,90.0,manual,shaft,2,1399000.0,2022,adventure,naked,vtwin,2
4,italy,Italy,tuono 1100,1077.0,175.0,121.0,manual,shaft,2,1999000.0,2022,adventure,naked,vtwin,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352,uk,UK,razorback,250.0,20.0,18.0,manual,chain,1,699000.0,2022,retroinspired,bobber,singlecylinder aircooled,1
353,uk,UK,rs-13,250.0,20.0,18.0,manual,chain,1,679000.0,2022,retroinspired,cafe racer,singlecylinder aircooled,1
354,uk,UK,sabbath,250.0,20.0,18.0,manual,chain,1,749000.0,2022,retroinspired,cruiser,singlecylinder aircooled,1
360,italy,Italy,x-cape,649.0,60.8,62.0,manual,parallel twin,2,720000.0,2023,modern,adventure touring,liquidcooled dohc,2
361,italy,Italy,seiemmezzo 6 ½,649.0,55.7,58.0,manual,parallel twin,2,689000.0,2023,retro,naked,liquidcooled dohc,2

In [224]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 305 entries, 0 to 361
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              305 non-null    object
 1   country_of_origin    305 non-null    object
 2   model                305 non-null    object
 3   number_of_cc         305 non-null    float64
 4   horsepower           305 non-null    float64
 5   torque               305 non-null    float64
 6   transmission_type    305 non-null    object
 7   drivetrain           305 non-null    object
 8   seating              305 non-null    int64
 9   price                305 non-null    float64
 10  year                 305 non-null    int64
 11  looks                305 non-null    object
 12  body_type            305 non-null    object
 13  engine_type          305 non-null    object
 14  number_of_cylinders  305 non-null    int64
dtypes: float64(4), int64(3), object(8)
memory usage: 38.1+ KB

In [227]:
df_cleaned.shape

(305, 15)

In [225]:
df_cleaned.isna().sum()

company                0
country_of_origin      0
model                  0
number_of_cc           0
horsepower             0
torque                 0
transmission_type      0
drivetrain             0
seating                0
price                  0
year                   0
looks                  0
body_type              0
engine_type            0
number_of_cylinders    0
dtype: int64

In [229]:
df.duplicated().sum()

np.int64(0)

In [230]:
df_cleaned.to_csv('clean_df.csv')